name : Check for Stage And Prod

on:
  push:
    branches:
      - "main"
      - "*"
  workflow_dispatch:

jobs:
  setEnv:
    runs-on: ubuntu-latest
    env:
      deploy : stage
      branch : no-br
    outputs:
      environment: ${{ env.deploy }}
      branch: ${{ env.branch }}
    steps:
      - name: Determine Deployment Environment
        run: |
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to production"
            echo "deploy=production" >> $GITHUB_ENV
          else
            echo "Deploying to staging"
            echo "deploy=staging" >> $GITHUB_ENV
          fi

  BuildJob:
    runs-on: ubuntu-latest
    needs : setEnv
    environment: ${{ needs.setEnv.outputs.environment }}
    env:
      environment: ${{ needs.setEnv.outputs.environment }}
      branch : ${{ needs.setEnv.outputs.branch }}
    steps:
      - name : Run ENVIRONMENT
        run: |
                # Replace with your deployment script or commands
                echo " ${{ secrets.AWS_BUCKET }} "
                if [[ "$environment" == "production" ]]; then
                  # Production deployment commands
                  echo "Deploying to production... on $branch"
                  # ...
                else
                  # Staging deployment commands
                  echo "Deploying to staging... on $branch"
                  # ...
                fi
