name : Check for Stage And Prod

on:
  push:
    branches:
      - "main"
      - "*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  setEnv:
    runs-on: ubuntu-latest
    env:
      deploy : stage
    outputs:
      environment: ${{ env.deploy }}
    steps:
      - name: Determine Deployment Environment
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "Deploying to production"
            echo "deploy=production" >> $GITHUB_ENV
          else
            echo "Deploying to staging"
            echo "deploy=staging" >> $GITHUB_ENV
          fi

  BuildJob:
    runs-on: ubuntu-latest
    needs : setEnv
    environment: $ {{ needs.SetDeployEnv.outputs.environment }}
    env:
      environment: $ {{ needs.SetDeployEnv.outputs.environment }}
    steps:
      - name : Run ENVIRONMENT
        run: |
                # Replace with your deployment script or commands
                if [[ "${{ env.environment }}" == "production" ]]; then
                  # Production deployment commands
                  echo "Deploying to production..."
                  # ...
                else
                  # Staging deployment commands
                  echo "Deploying to staging..."
                  # ...
                fi
