name : Check for Stage And Prod

on:
  push:
    branches:
      - "main"
      - "*"
  workflow_dispatch:

jobs:
  setEnv:
    runs-on: ubuntu-latest
    env:
      deploy : stage
    outputs:
      environment: ${{ env.deploy }}
      branch: ${{ github.ref##*/ }}
    steps:
      - name: Determine Deployment Environment
        run: |
          echo
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to production"
            echo "deploy=production" >> $GITHUB_ENV
          else
            echo "Deploying to staging"
            echo "deploy=staging" >> $GITHUB_ENV
          fi

  BuildJob:
    runs-on: ubuntu-latest
    needs : setEnv
    environment: ${{ needs.setEnv.outputs.environment }}
    env:
      environment: ${{ needs.setEnv.outputs.environment }}
      branch : $ {{ needs.setEnv.outputs.branch }}
    steps:
      - name : Run ENVIRONMENT
        run: |
                # Replace with your deployment script or commands
                if [[ "$environment" == "production" ]]; then
                  # Production deployment commands
                  echo "Deploying to production... on ${{ env.branch }}"
                  # ...
                else
                  # Staging deployment commands
                  echo "Deploying to staging...${{ env.branch }}"
                  # ...
                fi
